### ISSUE TITLE
Showing while click on tab

### ISSUE THREAD

**Issue by pushpendra07** [mygento/module-metrika#1]
Hello,

When we click on tab then it's showing below error for more information check below video.

Exception #0 (ReflectionException): Class Mygento\Base\Model\Source\Attributes does not exist

https://www.useloom.com/share/8662204ac780427d81b0d21226d72180

**Comment by luckyraul** [comment]
do you have such file https://github.com/mygento/base/blob/m2/Model/Source/Attributes.php ?

**Comment by pushpendra07** [comment]
No, Don't have such type files or module.

**Comment by luckyraul** [comment]
install with composer 
"mygento/module-metrika": "2.2.*"

**Comment by pushpendra07** [comment]
Can you give me the full command of the composer?

**Comment by luckyraul** [comment]
composer require "mygento/module-metrika":"2.2.*"
