### ISSUE TITLE
Magento CSP Warning при загрузке скрипта счетчика с mc.yandex.ru

### ISSUE THREAD

**Issue by MaxKhlupnov** [mygento/module-metrika#10]
`Refused to load the script 'https://mc.yandex.ru/metrika/watch.js' because it violates the following Content Security Policy directive: "script-src assets.adobedtm.com secure.authorize.net test.authorize.net geostag.cardinalcommerce.com 1eafstag.cardinalcommerce.com geoapi.cardinalcommerce.com 1eafapi.cardinalcommerce.com songbird.cardinalcommerce.com includestest.ccdc02.com www.googleadservices.com www.google-analytics.com www.paypalobjects.com js.braintreegateway.com www.paypal.com www.sandbox.paypal.com t.paypal.com s.ytimg.com video.google.com vimeo.com www.vimeo.com www.youtube.com *.payments-amazon.com *.payments-amazon.co.uk *.payments-amazon.co.jp *.payments-amazon.jp *.payments-amazon.it *.payments-amazon.fr *.payments-amazon.es *.payments-amazon.de *.trackedlink.net *.trackedweb.net *.dotdigital-pages.com cdn.dnky.co api.comapi.com webchat.dotdigital.com *.yotpo.com 'self' 'unsafe-inline' 'unsafe-eval'". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.`

![image](https://user-images.githubusercontent.com/11292800/194217740-316d27fd-ab5a-4299-85e9-aa80f6645103.png)

**Comment by luckyraul** [comment]
closed by #12. Test it

Thank you.
