### ISSUE TITLE
Модуль не работает на версии M2.3.6

### ISSUE THREAD

**Issue by its24** [mygento/module-metrika#6]
После установки в админ панели белое поле, в консоле ошибок нет. Модуль не работает на версии M2.3.6

**Comment by luckyraul** [comment]
через composer?

**Comment by its24** [comment]
Нет

**Comment by its24** [comment]
Ошибка через composer require mygento/module-metrika:2.*
PHP Fatal error:  Uncaught Error: Undefined class constant 'PRE_COMMAND_RUN' in /var/www/www-root/data/www/site.ru/vendor/laminas/laminas-dependency-plugin/src/DependencyRewriterPlugin.php:63
Stack trace:
#0 /usr/share/php/Composer/EventDispatcher/EventDispatcher.php(378): Laminas\DependencyPlugin\DependencyRewriterPlugin::getSubscribedEvents()
#1 /usr/share/php/Composer/Plugin/PluginManager.php(239): Composer\EventDispatcher\EventDispatcher->addSubscriber(Object(Laminas\DependencyPlugin\DependencyRewriterPlugin))
#2 /usr/share/php/Composer/Plugin/PluginManager.php(205): Composer\Plugin\PluginManager->addPlugin(Object(Laminas\DependencyPlugin\DependencyRewriterPlugin))
#3 /usr/share/php/Composer/Plugin/PluginManager.php(261): Composer\Plugin\PluginManager->registerPackage(Object(Composer\Package\CompletePackage))
#4 /usr/share/php/Composer/Plugin/PluginManager.php(76): Composer\Plugin\PluginManager->loadRepository(Object(Composer\Repository\InstalledFilesystemRepository))
#5 /usr/share/php/Composer/Factory.php(384) in /var/www/www-root/data/www/site.ru/vendor/laminas/laminas-dependency-plugin/src/DependencyRewriterPlugin.php on line 63

**Comment by luckyraul** [comment]
https://magento.stackexchange.com/questions/312566/undefined-class-constant-pre-command-run-while-upgrade-to-magento-2-3-5-from-m
